name: Rust

on: [push]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2 
    - uses: actions-rs/toolchain@v1
      with:
        toolchain: stable
    - name: Run cargo check
      uses: actions-rs/cargo@v1
      with:
        command: check
#     - name: Run tests
#       run: cargo test --verbose  
